# Generated by Django 5.0.2 on 2024-02-25 08:08

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_picture_postfilecontent_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=1, upload_to=post.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
