# Generated by Django 5.0.2 on 2024-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorites'),
        ('post', '0004_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='post.post'),
        ),
    ]
